#!/usr/bin/env bash
# Instaling Nginx


echo -e "Updating, installing and starting Nginx\n"
sudo apt-get -y  update
sudo apt-get -y  install nginx
sudo service nginx start

echo -e "\nSetting up.\n"

# nginx on FireWall
sudo ufw allow "Nginx HTTP"

# Give ownership to the user 
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

#backing up
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.backup

# new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

#Restarting ngnix
sudo service nginx restart

echo -e "\nCompleted.\n"
