#!/usr/bin/env bash
# installs nginx

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
