#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt -y upgrade
sudo apt -y install nginx

echo 'server {
    listen 80;
    server_name _;

    location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        add_header X-Served-By $HOSTNAME;
        root /var/www/html;
        index index.html;
        error_page 404 /error.html;
    }
}' | sudo tee /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/error.html

sudo bash -c "echo 'Hello, World!' > /var/www/html/index.html"
sudo service nginx restart
