#!/usr/bin/env bash
# Displays The content of the current directory
# Where only the part of the name after the first dash is displayed
# In a list format

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
